version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Europe/Budapest"
    open-pull-requests-limit: 5
    rebase-strategy: auto
    labels:
      - "dependencies"
      - "automated"
