name: ProTipp V2 CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Linting
        run: bun run lint || npx tsc --noEmit

      - name: Run Tests
        run: bun test:run || bunx vitest run --reporter=verbose

      - name: Build Project
        run: bun run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Install Netlify CLI
        run: npm install -g netlify-cli
          
      - name: Deploy to Netlify
        run: netlify deploy --prod --dir=.next --build
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

  preview:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy preview to Netlify
        id: netlify_preview
        shell: bash
        run: |
          set -e
          OUT=$(netlify deploy --dir=.next --build --json)
          echo "$OUT"
          # Extract deploy_url from JSON output using a more robust method
          URL=$(echo "$OUT" | sed -n 's/.*"deploy_url":"\([^"]*\)".*/\1/p')
          if [ -z "$URL" ]; then
            echo "Warning: Could not extract deploy_url from output"
            echo "Trying alternative extraction method..."
            URL=$(echo "$OUT" | grep -o 'https://[^"]*--protipp\.netlify\.app')
          fi
          if [ -z "$URL" ]; then
            echo "Error: Could not extract deploy_url from output"
            echo "Full output: $OUT"
            exit 1
          fi
          echo "PREVIEW_URL=$URL" >> $GITHUB_ENV
          echo "Preview URL: $URL"
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

      - name: Comment preview URL on PR
        uses: actions/github-script@v7
        with:
          script: |
            const url = process.env.PREVIEW_URL || ''
            const number = context.payload.pull_request?.number
            if (url && number) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: number,
                body: `🚀 Preview deploy: ${url}`
              })
            } else {
              core.warning('Preview URL not found; see job logs for details.')
            }
