name: Linear PR sync

on:
  pull_request:
    types: [opened, reopened]

jobs:
  create-linear-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Linear story via GraphQL
        shell: bash
        run: |
          set -e
          if [ -z "$LINEAR_API_KEY" ] || [ -z "$LINEAR_TEAM_ID" ]; then
            echo "Missing LINEAR_API_KEY or LINEAR_TEAM_ID" >&2
            exit 1
          fi
          TITLE="PR: ${PR_TITLE}"
          DESC="GitHub PR: ${PR_URL}\n\n${PR_BODY}"
          read -r -d '' QUERY <<'EOF'
          mutation IssueCreate($input: IssueCreateInput!) {
            issueCreate(input: $input) {
              success
              issue { id identifier url }
            }
          }
          EOF
          JSON=$(jq -n --arg q "$QUERY" \
                    --arg team "$LINEAR_TEAM_ID" \
                    --arg title "$TITLE" \
                    --arg desc "$DESC" \
                    '{query:$q, variables:{input:{teamId:$team, title:$title, description:$desc, priority:3}}}')
          curl -sS https://api.linear.app/graphql \
            -H "Content-Type: application/json" \
            -H "Authorization: ${LINEAR_API_KEY}" \
            -d "$JSON" | tee response.json
          echo "Response saved to response.json"
        env:
          LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
          LINEAR_TEAM_ID: ${{ secrets.LINEAR_TEAM_ID }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_BODY: ${{ github.event.pull_request.body }}
